<?php

namespace ContainerFNbwxxA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequirementsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\RequirementsController' shared autowired service.
     *
     * @return \App\Controller\RequirementsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/RequirementsController.php';

        $container->services['App\\Controller\\RequirementsController'] = $instance = new \App\Controller\RequirementsController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\RequirementsController', $container));

        return $instance;
    }
}
