security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    WebWMS\Security\V3\SecurityUser: 'auto'
  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    legacy_user_provider:
      entity:
        class: WebWMS\Entity\User
        property: username
    v3_user_provider:
      id: WebWMS\Security\V3\DbalUserProvider
    app_user_provider:
      chain:
        providers: [v3_user_provider, legacy_user_provider]
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api_v3:
      pattern: ^/api/v3
      stateless: true
      custom_authenticator: WebWMS\Integration\Infrastructure\Api\ApiKeyAuthenticator
      entry_point: WebWMS\Integration\Infrastructure\Api\ApiKeyAuthenticator
    v3:
      pattern: ^/v3
      provider: v3_user_provider
      context: webwms
      custom_authenticator: WebWMS\Security\V3\LoginFormAuthenticator
      entry_point: WebWMS\Security\V3\LoginFormAuthenticator
      logout:
        path: app_v3_logout
        target: app_v3_login
    main:
      lazy: true
      provider: app_user_provider
      context: webwms
      form_login:
        login_path: app_login
        check_path: app_login
        default_target_path: /
        always_use_default_target_path: true
      custom_authenticator:
        - WebWMS\Security\WebWmsAuthenticator
      # configure the form authentication as the entry point for unauthenticated users
      entry_point: form_login
      logout:
        path: app_logout
        # where to redirect after logout
        target: /
      
      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#the-firewall
      
      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true
    twig_inspector:
      pattern: ^/_template/
      security: false
  
  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/api/v3, roles: ROLE_API_CLIENT }
    - { path: ^/v3/login$, roles: PUBLIC_ACCESS }
    - { path: ^/v3, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/homepage, roles: [ IS_AUTHENTICATED_FULLY, ROLE_SUPER_ADMIN, ROLE_ADMIN ] }
#        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

when@test:
  security:
    password_hashers:
      # By default, password hashers are resource intensive and take time. This is
      # important to generate secure password hashes. In tests however, secure hashes
      # are not important, waste resources and increase test times. The following
      # reduces the work factor to the lowest possible values.
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
      WebWMS\Security\V3\SecurityUser:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
