image: php

definitions:
  steps:
    - step: &code-style
        name: Code Style Check (PHP CS)
        caches:
          - composer
        script:
          - echo ${BITBUCKET_CLONE_DIR}
          - mkdir -pv ${BITBUCKET_CLONE_DIR}/test-reports
          - cd ${BITBUCKET_CLONE_DIR}/
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          - vendor/bin/php-cs-fixer fix --dry-run --using-cache=no -vvv --show-progress=dots --allow-risky=yes
        artifacts:
          - test-reports/**

    - step: &code-analysis
        name: Code Analysis
        caches:
          - composer
        script:
          - mkdir -pv ${BITBUCKET_CLONE_DIR}/test-reports
          - cd ${BITBUCKET_CLONE_DIR}/
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          - composer install --ignore-platform-reqs --no-scripts
          - php -d memory_limit=-1 vendor/bin/phpstan analyse --configuration ./phpstan.neon --error-format=junit > ${BITBUCKET_CLONE_DIR}/test-reports/code-analysis-junit.xml
        artifacts:
          - test-reports/**

    - step: &var-dump-find
        name: Find dump messages
        caches:
          - composer
        script:
          - mkdir -pv ${BITBUCKET_CLONE_DIR}/test-reports
          - cd ${BITBUCKET_CLONE_DIR}/
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          - composer install --ignore-platform-reqs --no-scripts
          - vendor/bin/var-dump-check --symfony --laravel --doctrine --exclude vendor .
    
    - step: &vulnerability-scan
        name: Dependency Vulnerability Scan
        caches:
          - composer
        script:
          - cd ${BITBUCKET_CLONE_DIR}/
          - >
            curl -s https://api.github.com/repos/fabpot/local-php-security-checker/releases/latest \
                | grep "browser_download_url.*_linux_amd64" \
                | cut -d: -f 2,3 \
                | tr -d \" \
                | xargs -I % curl %  -L --output local-php-security-checker
          - chmod +x local-php-security-checker
          - ./local-php-security-checker
    
    - step: &mess-detector
        name: PHP Mess Detector (phpmd)
        caches:
          - composer
        script:
          - mkdir -pv ${BITBUCKET_CLONE_DIR}/test-reports
          - cd ${BITBUCKET_CLONE_DIR}/
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          - composer install --ignore-platform-reqs --no-scripts
          - vendor/bin/phpmd './src/,./bundles/' ansi rulesets.xml
        artifacts:
          - test-reports/**
    
    - step: &unit-tests
        name: Unit Tests
        caches:
          - composer
        script:
          - mkdir -pv ${BITBUCKET_CLONE_DIR}/test-reports
          - cd ${BITBUCKET_CLONE_DIR}/
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          - composer install --ignore-platform-reqs --no-scripts
          - vendor/bin/phpunit --coverage-html="./test-reports"
        artifacts:
          - test-reports/**

    - step: &build-deploy
        name: Build and Deploy
        script:
          - rsync -rzhv --delete --stats ssh --exclude 'ci/rsync.exclude' $SSH_USER@$SSH_HOST:$HOST_DIR
          - pipe: atlassian/rsync-deploy:0.8.1
            variables:
              USER: $SSH_USER
              SERVER: $SSH_HOST
              REMOTE_PATH: $HOST_DIR
              LOCAL_PATH: ${BITBUCKET_CLONE_DIR}/
              # SSH_KEY: '<string>' # Optional.
              # SSH_PORT: '<string>' # Optional.
              # SSH_ARGS: '<string>' # Optional.
              # EXTRA_ARGS: '<string>' # Optional.
              # DEBUG: '<boolean>' # Optional.
              # DELETE_FLAG: '<boolean>' # Optional.
pipelines:
  default:
    - step:
        name: Composer
        image: composer:2
        caches:
          - composer
        script:
          - cd ${BITBUCKET_CLONE_DIR}/
          - apk update && apk add gettext
          - ci/set-env.sh
          - composer install --ignore-platform-reqs
    - parallel:
        - step: *code-style
        - step: *code-analysis
        - step: *var-dump-find
        - step: *vulnerability-scan
        - step: *mess-detector
        - step: *unit-tests
    - step:
        <<: *build-deploy
        deployment: dev
        trigger: manual
  branches:
    main:
      - step: *code-style
      - step: *code-analysis
      - step: *var-dump-find
      - step: *unit-tests
      - step:
          <<: *build-deploy
          deployment: stg
          trigger: manual
  # CUSTOM Pipelines: Only triggered manually
  custom:
    vulnerability-scan:
      - step:
          <<: *vulnerability-scan
    production:
      - step:
          <<: *build-deploy
          deployment: prod
    staging:
      - step:
          <<: *build-deploy
          deployment: stg
    development:
      - step:
          <<: *build-deploy
          deployment: dev
