image: php:8.1

definitions:
  steps:
    - step: &code-style
        name: Code Style Check (PHP CS)
        caches:
          - composer
        script:
          - echo ${BITBUCKET_CLONE_DIR}
          - mkdir -pv ${BITBUCKET_CLONE_DIR}/test-reports
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          - vendor/bin/php-cs-fixer fix --dry-run --using-cache=no -vvv --show-progress=dots --allow-risky=yes
        artifacts:
          - test-reports/**

    - step: &code-analysis
        name: Code Analysis
        caches:
          - composer
        script:
          - mkdir -pv ${BITBUCKET_CLONE_DIR}/test-reports
          - cd /var/www/html/
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          - composer install --ignore-platform-reqs --no-scripts
          - php -d memory_limit=-1 vendor/bin/phpstan analyse --configuration ./phpstan.neon --error-format=junit > ${BITBUCKET_CLONE_DIR}/test-reports/code-analysis-junit.xml
        artifacts:
          - test-reports/**

    - step: &var-dump-find
        name: Find dump messages
        caches:
          - composer
        script:
          - mkdir -pv ${BITBUCKET_CLONE_DIR}/test-reports
          - cd /var/www/html/
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          - composer install --ignore-platform-reqs --no-scripts
          - vendor/bin/var-dump-check --symfony --laravel --doctrine --exclude vendor .
    
    - step: &vulnerability-scan
        name: Dependency Vulnerability Scan
        caches:
          - composer
        script:
          - cd /var/www/html/
          - >
            curl -s https://api.github.com/repos/fabpot/local-php-security-checker/releases/latest \
                | grep "browser_download_url.*_linux_amd64" \
                | cut -d: -f 2,3 \
                | tr -d \" \
                | xargs -I % curl %  -L --output local-php-security-checker
          - chmod +x local-php-security-checker
          - ./local-php-security-checker
    
    - step: &mess-detector
        name: PHP Mess Detector (phpmd)
        caches:
          - composer
        script:
          - mkdir -pv ${BITBUCKET_CLONE_DIR}/test-reports
          - cd /var/www/html/
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          - composer install --ignore-platform-reqs --no-scripts
          - vendor/bin/phpmd './src/,./bundles/' ansi rulesets.xml
        artifacts:
          - test-reports/**
    
    - step: &unit-tests
        name: Unit Tests
        caches:
          - composer
        script:
          - mkdir -pv ${BITBUCKET_CLONE_DIR}/test-reports
          - cd /var/www/html/
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          - composer install --ignore-platform-reqs --no-scripts
          - vendor/bin/phpunit --coverage-html="./test-reports"
        artifacts:
          - test-reports/**

    - step: &build-deploy
        name: Build and Deploy
        caches:
          - composer
        script:
          # set environment variables and export it to `.env.{stage}`
          - ci/set-env.sh
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          # install application dependencies
          - APP_ENV=${BITBUCKET_DEPLOYMENT_ENVIRONMENT} composer install --prefer-dist --optimize-autoloader --ignore-platform-reqs
        artifacts:
          - app/.env.*
pipelines:
  default:
    - step:
        name: Composer
        image: composer:2
        caches:
          - composer
        script:
          - apt-get update && apt-get install unzip gettext-base -y
          - ci/set-env.sh
          - composer install --ignore-platform-reqs
    - parallel:
        - step: *code-style
        - step: *code-analysis
        - step: *var-dump-find
        - step: *vulnerability-scan
        - step: *mess-detector
        - step: *unit-tests
    - step:
        <<: *build-deploy
        deployment: dev
        trigger: manual
  branches:
    main:
      - step: *code-style
      #- step: *unit-tests
      - step: *code-analysis
      #- step: *var-dump-find
      - step:
          <<: *build-deploy
          deployment: stg
          trigger: manual
  # CUSTOM Pipelines: Only triggered manually
  custom:
    vulnerability-scan:
      - step:
          <<: *vulnerability-scan
    
    production:
      - step:
          <<: *build-deploy
          deployment: prod
    
    staging:
      - step:
          <<: *build-deploy
          deployment: stg
    
    development:
      - step:
          <<: *build-deploy
          deployment: dev
