image: php:8.1.18-fpm

definitions:
  steps:
    - step: &code-style
        name: Code Style Check (PHP CS)
        image: composer:2
        caches:
          - composer
        script:
          - echo ${BITBUCKET_CLONE_DIR}
          - apk update && apk add gettext
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          - composer install --ignore-platform-reqs --no-scripts
          - vendor/bin/php-cs-fixer fix --dry-run --using-cache=no -vvv --show-progress=dots --allow-risky=yes

    - step: &code-analysis
        name: Code Analysis
        image: composer:2
        caches:
          - composer
        script:
          - mkdir -pv ${BITBUCKET_CLONE_DIR}/test-reports
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          - composer install --ignore-platform-reqs --no-scripts
          - php -d memory_limit=-1 vendor/bin/phpstan analyse --configuration ./phpstan.neon --error-format=junit > ${BITBUCKET_CLONE_DIR}/test-reports/code-analysis-junit.xml
        artifacts:
          - test-reports/**

    - step: &var-dump-find
        name: Find dump messages
        image: composer:2
        caches:
          - composer
        script:
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          - composer install --ignore-platform-reqs --no-scripts
          - vendor/bin/var-dump-check --symfony --laravel --doctrine --exclude vendor .

    - step: &vulnerability-scan
        name: Dependency Vulnerability Scan
        image: composer:2
        caches:
          - composer
        script:
          - >
            curl -s https://api.github.com/repos/fabpot/local-php-security-checker/releases/latest \
                | grep "browser_download_url.*_linux_amd64" \
                | cut -d: -f 2,3 \
                | tr -d \" \
                | xargs -I % curl %  -L --output local-php-security-checker
          - chmod +x local-php-security-checker
          - ./local-php-security-checker

    - step: &mess-detector
        name: PHP Mess Detector (phpmd)
        image: composer:2
        caches:
          - composer
        script:
          - mkdir -pv ${BITBUCKET_CLONE_DIR}/test-reports
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          - composer install --ignore-platform-reqs --no-scripts
          - vendor/bin/phpmd './src/,./module/' ansi rulesets.xml
        artifacts:
          - test-reports/**

    - step: &twig-lint
        name: Check Templates
        image: composer:2
        caches:
          - composer
        script:
          - /bin/bash ci/webwms-env.sh
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          - composer install --ignore-platform-reqs --no-scripts
          - bin/console lint:twig templates
        artifacts:
          - .env
    
    - step: &yaml-lint
        name: Yaml lint
        image: composer:2
        caches:
          - composer
        script:
          - mkdir -pv ${BITBUCKET_CLONE_DIR}/test-reports
          - /bin/bash ci/webwms-env.sh
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          - composer install --ignore-platform-reqs --no-scripts
          - bin/console lint:yaml config --parse-tags
        artifacts:
          - .env
          - test-reports/**

    - step: &unit-tests
        name: Unit Tests
        image: composer:2
        caches:
          - composer
        script:
          - mkdir -pv ${BITBUCKET_CLONE_DIR}/test-reports
          - composer config bitbucket-oauth.bitbucket.org ${BITBUCKET_OAUTH_CONSUMER_KEY} ${BITBUCKET_OAUTH_CONSUMER_SECRET}
          - composer install --ignore-platform-reqs --no-scripts
          - vendor/bin/phpunit --coverage-html="./test-reports"
        artifacts:
          - test-reports/**

    - step: &build-deploy
        name: Build and Deploy
        script:
          - export ENVIRONMENT_DIR=${ENVIRONMENT_DIR}
          - echo ${BITBUCKET_CLONE_DIR}
          - echo
          - apt-get update && apt-get install -y openssh-client rsync
#          - scp -r $BITBUCKET_CLONE_DIR/* $SSH_USER@$SSH_HOST:$HOST_DIR
#          - ssh $SSH_USER@$SSH_HOST
#          - cd $HOST_DIR
#          - git clone -b $BITBUCKET_BRANCH https://$BITBUCKET_USER@bitbucket.org/softdev-nord/webwms.git
#          - /bin/bash ci/webwms-env.sh
#          - pipe: atlassian/scp-deploy:1.5.0
#            variables:
#              USER: $SSH_USER
#              SERVER: $SSH_HOST
#              REMOTE_PATH: $HOST_DIR
#              LOCAL_PATH: $BITBUCKET_CLONE_DIR/*
          - pipe: atlassian/ssh-run:0.4.2
            variables:
              SSH_USER: $SSH_USER
              SERVER: $SSH_HOST
              MODE: 'script'
              COMMAND: 'ci/deploy.sh'
              DEBUG: 'true'
        artifacts:
          - build/*
pipelines:
  default:
    - parallel:
        - step: *code-style
        - step: *code-analysis
        - step: *var-dump-find
#        - step: *vulnerability-scan
        - step: *mess-detector
        - step: *twig-lint
        - step: *yaml-lint
        - step: *unit-tests
    - step:
        <<: *build-deploy
        name: Deploy to Development
        deployment: dev
        trigger: manual
    - step:
        <<: *build-deploy
        name: Deploy to Staging
        deployment: stg
        trigger: manual
  branches:
    main:
      - step: *code-style
      - step: *code-analysis
      - step: *var-dump-find
      - step: *unit-tests
      - step:
          <<: *build-deploy
          deployment: stg
          trigger: manual
  # CUSTOM Pipelines: Only triggered manually
  custom:
    vulnerability-scan:
      - step:
          <<: *vulnerability-scan
    development:
      - step:
          <<: *build-deploy
          deployment: dev
    staging:
      - step:
          <<: *build-deploy
          deployment: stg
    production:
      - step:
          <<: *build-deploy
          deployment: prod
