---
composer: false  # Analyse the composer.* files
includes:  #  directory and files to analyze, relative to config file directory
    - "/"
excludes: # regex of files (or directory) to exclude from analyze
#    - ".docker"
extensions:
    - php
    - php8
report:
    html: "public/phpmetrics/"
    csv: "public/phpmetrics/report.csv"
    json: "public/phpmetrics/report.json"
    violations: "public/phpmetrics/violations.xml"
groups:
    - name: Component
      match: "!component!i"
    - name: Metric
      match: "!metric!i"