controllers:
    resource:
        path: ../../src/Controller/
        namespace: WebWMS\Controller
    type: attribute

warehouse_controllers:
    resource:
        path: ../../src/Warehouse/Presentation/
        namespace: WebWMS\Warehouse\Presentation
    type: attribute

administration_controllers:
    resource:
        path: ../../src/Administration/Presentation/
        namespace: WebWMS\Administration\Presentation
    type: attribute

inbound_controllers:
    resource:
        path: ../../src/Inbound/Presentation/
        namespace: WebWMS\Inbound\Presentation
    type: attribute

kernel:
    resource: WebWMS\Kernel
    type: attribute
