controllers:
    resource:
        path: ../../src/Controller/
        namespace: WebWMS\Controller
    type: attribute

modules_controllers:
    resource:
        path: ../../src/Modules/
        namespace: WebWMS\Modules
    type: attribute

kernel:
    resource: WebWMS\Kernel
    type: attribute