controllers:
    resource:
        path: ../../src/Controller/
        namespace: WebWMS\Controller
    type: attribute

warehouse_controllers:
    resource:
        path: ../../src/Warehouse/
        namespace: WebWMS\Warehouse
    type: attribute

administration_controllers:
    resource:
        path: ../../src/Administration/Presentation/
        namespace: WebWMS\Administration\Presentation
    type: attribute

inbound_controllers:
    resource:
        path: ../../src/Inbound/Presentation/
        namespace: WebWMS\Inbound\Presentation
    type: attribute

outbound_controllers:
    resource:
        path: ../../src/Outbound/
        namespace: WebWMS\Outbound
    type: attribute

integration_controllers:
    resource:
        path: ../../src/Integration/
        namespace: WebWMS\Integration
    type: attribute

platform_controllers:
    resource:
        path: ../../src/Platform/Presentation/
        namespace: WebWMS\Platform\Presentation
    type: attribute

fulfillment_controllers:
    resource:
        path: ../../src/Fulfillment/Presentation/
        namespace: WebWMS\Fulfillment\Presentation
    type: attribute

documentation_controllers:
    resource:
        path: ../../src/Documentation/Presentation/
        namespace: WebWMS\Documentation\Presentation
    type: attribute

kernel:
    resource: WebWMS\Kernel
    type: attribute
