<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260921230000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add advanced picking, internal transport, material flow and milk-run control';
    }

    public function up(Schema $schema): void
    {
        $options = ' DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB';
        $this->addSql('CREATE TABLE wms_pick_wave (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(120) NOT NULL, strategy VARCHAR(30) NOT NULL, selection_type VARCHAR(30) NOT NULL, selection_value VARCHAR(100) DEFAULT NULL, priority INT NOT NULL, planned_start_at DATETIME(6) DEFAULT NULL, status VARCHAR(30) NOT NULL, created_by CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL, released_by CHAR(36) DEFAULT NULL, released_at DATETIME(6) DEFAULT NULL, completed_at DATETIME(6) DEFAULT NULL, UNIQUE INDEX UNIQ_WMS_PICK_WAVE_CODE (tenant_id, code), INDEX IDX_WMS_PICK_WAVE_STATUS (tenant_id, status, priority), PRIMARY KEY(id), CONSTRAINT FK_WMS_PICK_WAVE_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_PICK_WAVE_CREATED_BY FOREIGN KEY (created_by) REFERENCES wms_user_account (id), CONSTRAINT FK_WMS_PICK_WAVE_RELEASED_BY FOREIGN KEY (released_by) REFERENCES wms_user_account (id))' . $options);
        $this->addSql('CREATE TABLE wms_pick_wave_list (wave_id CHAR(36) NOT NULL, pick_list_id CHAR(36) NOT NULL, container_code VARCHAR(50) NOT NULL, consolidation_status VARCHAR(30) NOT NULL, consolidated_by CHAR(36) DEFAULT NULL, consolidated_at DATETIME(6) DEFAULT NULL, UNIQUE INDEX UNIQ_WMS_PICK_WAVE_LIST (pick_list_id), UNIQUE INDEX UNIQ_WMS_PICK_WAVE_CONTAINER (wave_id, container_code), INDEX IDX_WMS_PICK_WAVE_LIST_WAVE (wave_id), PRIMARY KEY(wave_id, pick_list_id), CONSTRAINT FK_WMS_PICK_WAVE_LIST_WAVE FOREIGN KEY (wave_id) REFERENCES wms_pick_wave (id) ON DELETE CASCADE, CONSTRAINT FK_WMS_PICK_WAVE_LIST_PICK FOREIGN KEY (pick_list_id) REFERENCES wms_pick_list (id), CONSTRAINT FK_WMS_PICK_WAVE_LIST_USER FOREIGN KEY (consolidated_by) REFERENCES wms_user_account (id))' . $options);
        $this->addSql('CREATE TABLE wms_pick_scan_event (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, pick_task_id CHAR(36) NOT NULL, location_scan VARCHAR(100) NOT NULL, product_scan VARCHAR(100) NOT NULL, batch_scan VARCHAR(100) DEFAULT NULL, serial_scan VARCHAR(100) DEFAULT NULL, quantity INT NOT NULL, result VARCHAR(30) NOT NULL, message VARCHAR(255) NOT NULL, scanned_by CHAR(36) NOT NULL, scanned_at DATETIME(6) NOT NULL, INDEX IDX_WMS_PICK_SCAN_TASK (pick_task_id, scanned_at), INDEX IDX_WMS_PICK_SCAN_TENANT (tenant_id, scanned_at), PRIMARY KEY(id), CONSTRAINT FK_WMS_PICK_SCAN_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_PICK_SCAN_TASK FOREIGN KEY (pick_task_id) REFERENCES wms_pick_task (id), CONSTRAINT FK_WMS_PICK_SCAN_USER FOREIGN KEY (scanned_by) REFERENCES wms_user_account (id))' . $options);
        $this->addSql('CREATE TABLE wms_forklift (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, warehouse_id CHAR(36) NOT NULL, code VARCHAR(30) NOT NULL, name VARCHAR(100) NOT NULL, resource_type VARCHAR(30) NOT NULL, status VARCHAR(30) NOT NULL, assigned_user_id CHAR(36) DEFAULT NULL, last_location_id CHAR(36) DEFAULT NULL, created_by CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL, changed_at DATETIME(6) DEFAULT NULL, UNIQUE INDEX UNIQ_WMS_FORKLIFT_CODE (tenant_id, code), INDEX IDX_WMS_FORKLIFT_STATUS (tenant_id, status), PRIMARY KEY(id), CONSTRAINT FK_WMS_FORKLIFT_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_FORKLIFT_WAREHOUSE FOREIGN KEY (warehouse_id) REFERENCES wms_warehouse (id), CONSTRAINT FK_WMS_FORKLIFT_USER FOREIGN KEY (assigned_user_id) REFERENCES wms_user_account (id), CONSTRAINT FK_WMS_FORKLIFT_LOCATION FOREIGN KEY (last_location_id) REFERENCES wms_storage_location (id), CONSTRAINT FK_WMS_FORKLIFT_CREATED_BY FOREIGN KEY (created_by) REFERENCES wms_user_account (id))' . $options);
        $this->addSql('CREATE TABLE wms_transport_rule (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, code VARCHAR(30) NOT NULL, name VARCHAR(100) NOT NULL, trigger_type VARCHAR(30) NOT NULL, source_prefix VARCHAR(50) NOT NULL, target_prefix VARCHAR(50) NOT NULL, transport_type VARCHAR(30) NOT NULL, resource_type VARCHAR(30) NOT NULL, priority INT NOT NULL, enabled TINYINT(1) NOT NULL, created_by CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL, UNIQUE INDEX UNIQ_WMS_TRANSPORT_RULE_CODE (tenant_id, code), INDEX IDX_WMS_TRANSPORT_RULE_MATCH (tenant_id, trigger_type, enabled, priority), PRIMARY KEY(id), CONSTRAINT FK_WMS_TRANSPORT_RULE_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_TRANSPORT_RULE_CREATED_BY FOREIGN KEY (created_by) REFERENCES wms_user_account (id))' . $options);
        $this->addSql('CREATE TABLE wms_transport_order (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, code VARCHAR(50) NOT NULL, transport_type VARCHAR(30) NOT NULL, trigger_reference VARCHAR(100) DEFAULT NULL, product_id CHAR(36) DEFAULT NULL, source_location_id CHAR(36) NOT NULL, target_location_id CHAR(36) NOT NULL, quantity INT DEFAULT NULL, stock_status VARCHAR(30) DEFAULT NULL, batch_number VARCHAR(100) DEFAULT NULL, serial_number VARCHAR(100) DEFAULT NULL, expires_at DATE DEFAULT NULL, forklift_id CHAR(36) DEFAULT NULL, priority INT NOT NULL, due_at DATETIME(6) DEFAULT NULL, status VARCHAR(30) NOT NULL, created_by CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL, assigned_by CHAR(36) DEFAULT NULL, assigned_at DATETIME(6) DEFAULT NULL, started_by CHAR(36) DEFAULT NULL, started_at DATETIME(6) DEFAULT NULL, completed_by CHAR(36) DEFAULT NULL, completed_at DATETIME(6) DEFAULT NULL, transfer_id CHAR(36) DEFAULT NULL, UNIQUE INDEX UNIQ_WMS_TRANSPORT_CODE (tenant_id, code), UNIQUE INDEX UNIQ_WMS_TRANSPORT_TRANSFER (transfer_id), INDEX IDX_WMS_TRANSPORT_QUEUE (tenant_id, status, priority, due_at), PRIMARY KEY(id), CONSTRAINT FK_WMS_TRANSPORT_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_TRANSPORT_PRODUCT FOREIGN KEY (product_id) REFERENCES wms_product_reference (id), CONSTRAINT FK_WMS_TRANSPORT_SOURCE FOREIGN KEY (source_location_id) REFERENCES wms_storage_location (id), CONSTRAINT FK_WMS_TRANSPORT_TARGET FOREIGN KEY (target_location_id) REFERENCES wms_storage_location (id), CONSTRAINT FK_WMS_TRANSPORT_FORKLIFT FOREIGN KEY (forklift_id) REFERENCES wms_forklift (id), CONSTRAINT FK_WMS_TRANSPORT_CREATED_BY FOREIGN KEY (created_by) REFERENCES wms_user_account (id), CONSTRAINT FK_WMS_TRANSPORT_ASSIGNED_BY FOREIGN KEY (assigned_by) REFERENCES wms_user_account (id), CONSTRAINT FK_WMS_TRANSPORT_STARTED_BY FOREIGN KEY (started_by) REFERENCES wms_user_account (id), CONSTRAINT FK_WMS_TRANSPORT_COMPLETED_BY FOREIGN KEY (completed_by) REFERENCES wms_user_account (id))' . $options);
        $this->addSql('CREATE TABLE wms_process_station (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, warehouse_id CHAR(36) NOT NULL, location_id CHAR(36) NOT NULL, code VARCHAR(30) NOT NULL, name VARCHAR(100) NOT NULL, station_type VARCHAR(30) NOT NULL, sequence_number INT NOT NULL, active TINYINT(1) NOT NULL, created_by CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL, UNIQUE INDEX UNIQ_WMS_STATION_CODE (tenant_id, code), UNIQUE INDEX UNIQ_WMS_STATION_LOCATION (location_id), PRIMARY KEY(id), CONSTRAINT FK_WMS_STATION_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_STATION_WAREHOUSE FOREIGN KEY (warehouse_id) REFERENCES wms_warehouse (id), CONSTRAINT FK_WMS_STATION_LOCATION FOREIGN KEY (location_id) REFERENCES wms_storage_location (id), CONSTRAINT FK_WMS_STATION_CREATED_BY FOREIGN KEY (created_by) REFERENCES wms_user_account (id))' . $options);
        $this->addSql('CREATE TABLE wms_milk_run (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, code VARCHAR(30) NOT NULL, name VARCHAR(100) NOT NULL, warehouse_id CHAR(36) NOT NULL, schedule_type VARCHAR(20) NOT NULL, interval_minutes INT DEFAULT NULL, next_departure_at DATETIME(6) DEFAULT NULL, status VARCHAR(30) NOT NULL, created_by CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL, UNIQUE INDEX UNIQ_WMS_MILK_RUN_CODE (tenant_id, code), PRIMARY KEY(id), CONSTRAINT FK_WMS_MILK_RUN_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_MILK_RUN_WAREHOUSE FOREIGN KEY (warehouse_id) REFERENCES wms_warehouse (id), CONSTRAINT FK_WMS_MILK_RUN_CREATED_BY FOREIGN KEY (created_by) REFERENCES wms_user_account (id))' . $options);
        $this->addSql('CREATE TABLE wms_milk_run_stop (id CHAR(36) NOT NULL, milk_run_id CHAR(36) NOT NULL, station_id CHAR(36) NOT NULL, sequence_number INT NOT NULL, dwell_minutes INT NOT NULL, UNIQUE INDEX UNIQ_WMS_MILK_RUN_STOP_SEQUENCE (milk_run_id, sequence_number), UNIQUE INDEX UNIQ_WMS_MILK_RUN_STOP_STATION (milk_run_id, station_id), PRIMARY KEY(id), CONSTRAINT FK_WMS_MILK_RUN_STOP_RUN FOREIGN KEY (milk_run_id) REFERENCES wms_milk_run (id) ON DELETE CASCADE, CONSTRAINT FK_WMS_MILK_RUN_STOP_STATION FOREIGN KEY (station_id) REFERENCES wms_process_station (id))' . $options);
        $this->addSql('CREATE TABLE wms_fulfillment_event (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, aggregate_type VARCHAR(40) NOT NULL, aggregate_id CHAR(36) NOT NULL, event_type VARCHAR(50) NOT NULL, payload JSON NOT NULL, performed_by CHAR(36) NOT NULL, occurred_at DATETIME(6) NOT NULL, INDEX IDX_WMS_FULFILLMENT_EVENT (tenant_id, occurred_at), PRIMARY KEY(id), CONSTRAINT FK_WMS_FULFILLMENT_EVENT_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_FULFILLMENT_EVENT_USER FOREIGN KEY (performed_by) REFERENCES wms_user_account (id))' . $options);
        $this->addSql("INSERT IGNORE INTO wms_role_permission (role_id, permission_key) SELECT DISTINCT role_id, permission_key FROM wms_role_permission CROSS JOIN (SELECT 'fulfillment.pick.control' permission_key UNION ALL SELECT 'fulfillment.pick.optimize' UNION ALL SELECT 'fulfillment.pick.wave.write') permissions WHERE wms_role_permission.permission_key = 'fulfillment.pick.write'");
        $this->addSql("INSERT IGNORE INTO wms_role_permission (role_id, permission_key) SELECT DISTINCT role_id, permission_key FROM wms_role_permission CROSS JOIN (SELECT 'fulfillment.transport.assign' permission_key UNION ALL SELECT 'fulfillment.transport.configure' UNION ALL SELECT 'fulfillment.transport.execute' UNION ALL SELECT 'fulfillment.transport.read' UNION ALL SELECT 'fulfillment.transport.write' UNION ALL SELECT 'fulfillment.replenishment.execute' UNION ALL SELECT 'fulfillment.replenishment.read' UNION ALL SELECT 'fulfillment.replenishment.write') permissions WHERE wms_role_permission.permission_key = 'inventory.stock.transfer'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql("DELETE FROM wms_role_permission WHERE permission_key IN ('fulfillment.pick.control', 'fulfillment.pick.optimize', 'fulfillment.pick.wave.write', 'fulfillment.transport.assign', 'fulfillment.transport.configure', 'fulfillment.transport.execute', 'fulfillment.transport.read', 'fulfillment.transport.write', 'fulfillment.replenishment.execute', 'fulfillment.replenishment.read', 'fulfillment.replenishment.write')");
        $this->addSql('DROP TABLE wms_fulfillment_event');
        $this->addSql('DROP TABLE wms_milk_run_stop');
        $this->addSql('DROP TABLE wms_milk_run');
        $this->addSql('DROP TABLE wms_process_station');
        $this->addSql('DROP TABLE wms_transport_order');
        $this->addSql('DROP TABLE wms_transport_rule');
        $this->addSql('DROP TABLE wms_forklift');
        $this->addSql('DROP TABLE wms_pick_scan_event');
        $this->addSql('DROP TABLE wms_pick_wave_list');
        $this->addSql('DROP TABLE wms_pick_wave');
    }
}
