<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260923190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Complete platform control center, portal, billing, search, media and print routing';
    }

    public function up(Schema $schema): void
    {
        $o = ' DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB';
        $this->addSql('CREATE TABLE wms_shopfloor_task (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, code VARCHAR(50) NOT NULL, task_type VARCHAR(30) NOT NULL, title VARCHAR(150) NOT NULL, reference_type VARCHAR(40) DEFAULT NULL, reference_id CHAR(36) DEFAULT NULL, priority SMALLINT NOT NULL, status VARCHAR(20) NOT NULL, planned_for DATETIME(6) DEFAULT NULL, assigned_to CHAR(36) DEFAULT NULL, created_by CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL, changed_by CHAR(36) DEFAULT NULL, changed_at DATETIME(6) DEFAULT NULL, UNIQUE INDEX UNIQ_WMS_SHOPFLOOR_CODE (tenant_id, code), INDEX IDX_WMS_SHOPFLOOR_BOARD (tenant_id, status, priority, planned_for), PRIMARY KEY(id), CONSTRAINT FK_WMS_SHOPFLOOR_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_SHOPFLOOR_ASSIGNEE FOREIGN KEY (assigned_to) REFERENCES wms_user_account (id), CONSTRAINT FK_WMS_SHOPFLOOR_CREATED_BY FOREIGN KEY (created_by) REFERENCES wms_user_account (id), CONSTRAINT FK_WMS_SHOPFLOOR_CHANGED_BY FOREIGN KEY (changed_by) REFERENCES wms_user_account (id))' . $o);
        $this->addSql('CREATE TABLE wms_kpi_definition (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(120) NOT NULL, metric VARCHAR(50) NOT NULL, aggregation VARCHAR(20) NOT NULL, target_value DECIMAL(18,4) DEFAULT NULL, active TINYINT(1) NOT NULL, created_by CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL, UNIQUE INDEX UNIQ_WMS_KPI_CODE (tenant_id, code), PRIMARY KEY(id), CONSTRAINT FK_WMS_KPI_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_KPI_USER FOREIGN KEY (created_by) REFERENCES wms_user_account (id))' . $o);
        $this->addSql('CREATE TABLE wms_dashboard (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(120) NOT NULL, layout_json JSON NOT NULL, created_by CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL, UNIQUE INDEX UNIQ_WMS_DASHBOARD_CODE (tenant_id, code), PRIMARY KEY(id), CONSTRAINT FK_WMS_DASHBOARD_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_DASHBOARD_USER FOREIGN KEY (created_by) REFERENCES wms_user_account (id))' . $o);
        $this->addSql('CREATE TABLE wms_partner_account (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, business_partner_id CHAR(36) NOT NULL, user_id CHAR(36) NOT NULL, permissions JSON NOT NULL, active TINYINT(1) NOT NULL, created_by CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL, UNIQUE INDEX UNIQ_WMS_PARTNER_ACCOUNT_USER (tenant_id, user_id), INDEX IDX_WMS_PARTNER_ACCOUNT_PARTNER (business_partner_id), PRIMARY KEY(id), CONSTRAINT FK_WMS_PARTNER_ACCOUNT_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_PARTNER_ACCOUNT_PARTNER FOREIGN KEY (business_partner_id) REFERENCES wms_business_partner (id), CONSTRAINT FK_WMS_PARTNER_ACCOUNT_USER FOREIGN KEY (user_id) REFERENCES wms_user_account (id), CONSTRAINT FK_WMS_PARTNER_ACCOUNT_CREATED FOREIGN KEY (created_by) REFERENCES wms_user_account (id))' . $o);
        $this->addSql('CREATE TABLE wms_automation_rule (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(120) NOT NULL, event_name VARCHAR(100) NOT NULL, conditions_json JSON NOT NULL, action_type VARCHAR(30) NOT NULL, action_config JSON NOT NULL, active TINYINT(1) NOT NULL, created_by CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL, UNIQUE INDEX UNIQ_WMS_AUTOMATION_RULE_CODE (tenant_id, code), INDEX IDX_WMS_AUTOMATION_EVENT (tenant_id, event_name, active), PRIMARY KEY(id), CONSTRAINT FK_WMS_AUTOMATION_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_AUTOMATION_USER FOREIGN KEY (created_by) REFERENCES wms_user_account (id))' . $o);
        $this->addSql('CREATE TABLE wms_automation_execution (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, rule_id CHAR(36) NOT NULL, event_name VARCHAR(100) NOT NULL, event_payload JSON NOT NULL, status VARCHAR(20) NOT NULL, result_message VARCHAR(500) DEFAULT NULL, executed_by CHAR(36) NOT NULL, executed_at DATETIME(6) NOT NULL, INDEX IDX_WMS_AUTOMATION_EXECUTION (tenant_id, executed_at), PRIMARY KEY(id), CONSTRAINT FK_WMS_AUTOMATION_EXEC_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_AUTOMATION_EXEC_RULE FOREIGN KEY (rule_id) REFERENCES wms_automation_rule (id), CONSTRAINT FK_WMS_AUTOMATION_EXEC_USER FOREIGN KEY (executed_by) REFERENCES wms_user_account (id))' . $o);
        $this->addSql('CREATE TABLE wms_storage_fee_rule (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, business_partner_id CHAR(36) NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(120) NOT NULL, price_per_unit_day DECIMAL(18,4) NOT NULL, free_days SMALLINT UNSIGNED NOT NULL, currency CHAR(3) NOT NULL, active TINYINT(1) NOT NULL, created_by CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL, UNIQUE INDEX UNIQ_WMS_STORAGE_FEE_CODE (tenant_id, code), PRIMARY KEY(id), CONSTRAINT FK_WMS_STORAGE_FEE_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_STORAGE_FEE_PARTNER FOREIGN KEY (business_partner_id) REFERENCES wms_business_partner (id), CONSTRAINT FK_WMS_STORAGE_FEE_USER FOREIGN KEY (created_by) REFERENCES wms_user_account (id))' . $o);
        $this->addSql('CREATE TABLE wms_billable_line (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, business_partner_id CHAR(36) NOT NULL, source_type VARCHAR(30) NOT NULL, source_reference VARCHAR(100) NOT NULL, description VARCHAR(255) NOT NULL, quantity DECIMAL(18,4) NOT NULL, unit_price DECIMAL(18,4) NOT NULL, amount DECIMAL(18,4) NOT NULL, currency CHAR(3) NOT NULL, service_date DATE NOT NULL, status VARCHAR(20) NOT NULL, created_by CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL, INDEX IDX_WMS_BILLABLE_PARTNER (tenant_id, business_partner_id, status, service_date), PRIMARY KEY(id), CONSTRAINT FK_WMS_BILLABLE_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_BILLABLE_PARTNER FOREIGN KEY (business_partner_id) REFERENCES wms_business_partner (id), CONSTRAINT FK_WMS_BILLABLE_USER FOREIGN KEY (created_by) REFERENCES wms_user_account (id))' . $o);
        $this->addSql('CREATE TABLE wms_value_added_service (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(120) NOT NULL, unit VARCHAR(30) NOT NULL, unit_price DECIMAL(18,4) NOT NULL, currency CHAR(3) NOT NULL, active TINYINT(1) NOT NULL, created_by CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL, UNIQUE INDEX UNIQ_WMS_VAS_CODE (tenant_id, code), PRIMARY KEY(id), CONSTRAINT FK_WMS_VAS_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_VAS_USER FOREIGN KEY (created_by) REFERENCES wms_user_account (id))' . $o);
        $this->addSql('CREATE TABLE wms_search_document (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, document_type VARCHAR(40) NOT NULL, aggregate_id CHAR(36) NOT NULL, title VARCHAR(255) NOT NULL, body TEXT NOT NULL, route_name VARCHAR(100) DEFAULT NULL, route_parameters JSON NOT NULL, indexed_at DATETIME(6) NOT NULL, UNIQUE INDEX UNIQ_WMS_SEARCH_AGGREGATE (tenant_id, document_type, aggregate_id), FULLTEXT INDEX FTX_WMS_SEARCH_CONTENT (title, body), PRIMARY KEY(id), CONSTRAINT FK_WMS_SEARCH_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id))' . $o);
        $this->addSql('CREATE TABLE wms_media_asset (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, aggregate_type VARCHAR(40) NOT NULL, aggregate_id CHAR(36) NOT NULL, filename VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, byte_size INT UNSIGNED NOT NULL, checksum CHAR(64) NOT NULL, content LONGBLOB NOT NULL, captured_by CHAR(36) NOT NULL, captured_at DATETIME(6) NOT NULL, INDEX IDX_WMS_MEDIA_AGGREGATE (tenant_id, aggregate_type, aggregate_id), PRIMARY KEY(id), CONSTRAINT FK_WMS_MEDIA_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_MEDIA_USER FOREIGN KEY (captured_by) REFERENCES wms_user_account (id))' . $o);
        $this->addSql('CREATE TABLE wms_print_routing_rule (id CHAR(36) NOT NULL, tenant_id CHAR(36) NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(120) NOT NULL, document_type VARCHAR(40) NOT NULL, site_id CHAR(36) DEFAULT NULL, workstation VARCHAR(80) DEFAULT NULL, process_key VARCHAR(100) DEFAULT NULL, printer_id CHAR(36) NOT NULL, priority SMALLINT NOT NULL, active TINYINT(1) NOT NULL, created_by CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL, UNIQUE INDEX UNIQ_WMS_PRINT_ROUTE_CODE (tenant_id, code), INDEX IDX_WMS_PRINT_ROUTE_MATCH (tenant_id, document_type, active, priority), PRIMARY KEY(id), CONSTRAINT FK_WMS_PRINT_ROUTE_TENANT FOREIGN KEY (tenant_id) REFERENCES wms_tenant (id), CONSTRAINT FK_WMS_PRINT_ROUTE_SITE FOREIGN KEY (site_id) REFERENCES wms_site (id), CONSTRAINT FK_WMS_PRINT_ROUTE_PRINTER FOREIGN KEY (printer_id) REFERENCES wms_printer (id), CONSTRAINT FK_WMS_PRINT_ROUTE_USER FOREIGN KEY (created_by) REFERENCES wms_user_account (id))' . $o);
    }

    public function down(Schema $schema): void
    {
        foreach (['wms_print_routing_rule', 'wms_media_asset', 'wms_search_document', 'wms_billable_line', 'wms_value_added_service', 'wms_storage_fee_rule', 'wms_automation_execution', 'wms_automation_rule', 'wms_partner_account', 'wms_dashboard', 'wms_kpi_definition', 'wms_shopfloor_task'] as $table) {
            $this->addSql('DROP TABLE ' . $table);
        }
    }
}
