# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  php: circleci/php@1.1.0
  envsubst: sawadashota/envsubst@volatile

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    working_directory: /home/circleci
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/php:8.1.9
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    environment:
      CIRCLE_REPOSITORY_URL: https://softdev-nord:${BITBUCKET_PASSWORD}@bitbucket.org/softdev-nord/webwms.git
    steps:
      - php/install-composer
      - envsubst/install
      - run:
          name: "Checkout code"
          command: |
            cd $CIRCLE_WORKING_DIRECTORY && \
            git clone -b << pipeline.git.branch >> "$CIRCLE_REPOSITORY_URL"
      - run:
          name: "Setup custom environment variables (.env)"
          command: |
            cd webwms/
            ci/set-env.sh
      - run:
          name: "PHP Mess Detector"
          command: |
            cd webwms/  
            composer install --ignore-platform-reqs --no-scripts
            vendor/bin/phpmd ./src/ ansi rulesets.xml
      - run:
          name: "PHP CS Fixer"
          command: |
            cd webwms/  
            composer install --ignore-platform-reqs --no-scripts
            vendor/bin/php-cs-fixer fix --dry-run --using-cache=no -vvv --show-progress=dots
      - run:
            name: "PHP Static Analysis"
            command: |
                cd webwms/  
                composer install --ignore-platform-reqs --no-scripts
                vendor/bin/phpstan analyse
      - run:
            name: "Dependency Vulnerability Scan"
            command: |
                cd webwms/  
                curl -s https://api.github.com/repos/fabpot/local-php-security-checker/releases/latest \
                  | grep "browser_download_url.*_linux_amd64" \
                  | cut -d: -f 2,3 \
                  | tr -d \" \
                  | xargs -I % curl %  -L --output local-php-security-checker
                chmod +x local-php-security-checker
                ./local-php-security-checker
  deploy-dev:
    machine:
      enabled: true
    steps:
      - run: sudo apt update
      - run: sudo apt install openssh-client rsync
      - add_ssh_keys:
          fingerprints:
          - be:55:0b:e0:ad:c0:9a:e0:ca:da:f4:9d:6f:b1:7b:65
      - run: ssh-keyscan -H 178.20.100.70 >> ~/.ssh/known_hosts
#      - run: rsync -e -avvz --exclude=node_modules ssh -o "StrictHostKeyChecking=no" admin_sodeno@178.20.100.70:/webwms.softdev-nord.de
      - run:
          name: Deploy Over SSH
          command: |
            rsync -e ssh -avvz --exclude=node_modules admin_sodeno@178.20.100.70:/webwms.softdev-nord.de/


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
    build-deploy:
      jobs:
        - build
        - deploy-dev:
            requires:
              - build