#####################################################################
# CircleCI Konfiguration für webWMS
#
# (C)2022 SoftDev Nord Rene Irrgang
#####################################################################

# Verwende die neueste Version 2.1 des CircleCI Pipeline Process Engine.
# Siehe: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  php: circleci/php@1.1.0
  envsubst: sawadashota/envsubst@volatile

# Definiere einen Auftrag, der später in einem Workflow aufgerufen werden soll.
# Siehe: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    working_directory: /home/circleci
    # Gebe die Ausführungsumgebung an. Es kann ein Image von Dockerhub angeben werden
    # oder eines der Convenience Images aus dem Developer Hub von CircleCI verwendet werden.
    # Siehe: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/php:8.1.9
    # Schritte zum Job hinzufügen
    # Siehe: https://circleci.com/docs/2.0/configuration-reference/#steps
    environment:
      CIRCLE_REPOSITORY_URL: https://softdev-nord:${BITBUCKET_PASSWORD}@bitbucket.org/softdev-nord/webwms.git
    steps:
      - php/install-composer
      - run:
          name: "Checkout code"
          command: |
            cd $CIRCLE_WORKING_DIRECTORY && \
            git clone -b << pipeline.git.branch >> "$CIRCLE_REPOSITORY_URL"
      - run:
          name: "PHP Mess Detector"
          command: |
            cd webwms/  
            composer install --ignore-platform-reqs --no-scripts
            vendor/bin/phpmd './src/,./bundles/' ansi rulesets.xml
      - run:
          name: "PHP CS Fixer"
          command: |
            cd webwms/  
            composer install --ignore-platform-reqs --no-scripts
            vendor/bin/php-cs-fixer fix --dry-run --using-cache=no -vvv --show-progress=dots --allow-risky=yes
      - run:
            name: "PHP Static Analysis"
            command: |
                cd webwms/  
                composer install --ignore-platform-reqs --no-scripts
                vendor/bin/phpstan analyse
      - run:
            name: "Dependency Vulnerability Scan"
            command: |
                cd webwms/  
                curl -s https://api.github.com/repos/fabpot/local-php-security-checker/releases/latest \
                  | grep "browser_download_url.*_linux_amd64" \
                  | cut -d: -f 2,3 \
                  | tr -d \" \
                  | xargs -I % curl %  -L --output local-php-security-checker
                chmod +x local-php-security-checker
                ./local-php-security-checker

  deploy-development:
    working_directory: /home/circleci
    docker:
      - image: cimg/php:8.1.9
    environment:
      CIRCLE_REPOSITORY_URL: https://softdev-nord:${BITBUCKET_PASSWORD}@bitbucket.org/softdev-nord/webwms.git
    steps:
      - envsubst/install
      - run: sudo apt update
      - run: sudo apt install openssh-client rsync
      - run:
          name: "Checkout code"
          command: |
            cd $CIRCLE_WORKING_DIRECTORY && \
            git clone -b << pipeline.git.branch >> "$CIRCLE_REPOSITORY_URL"
      - run:
          name: "Setup custom environment variables (.env)"
          command: |
            cd webwms/
            ci/set-env.sh
      - add_ssh_keys:
          fingerprints:
            - 94:eb:8f:f3:8f:62:12:f3:22:04:c7:61:7e:5f:01:34
      - run: ssh-keyscan -H 178.20.100.70 >> ~/.ssh/authorized_keys
      - run:
          name: Deploy development over SSH
          command: |
            rsync -ae ssh --exclude 'ci/rsync.exclude' \
            /home/circleci/webwms/ \
            $SSH_USER@$SSH_HOST:/var/www/vhosts/softdev-nord.de/webwms-dev.softdev-nord.de
      - run:
          name: Composer install
          command: |
            cd webwms/
            composer install --ignore-platform-reqs
      - run:
          name: Clear the caches
          command: |
            cd webwms/
            php bin/console cache:clear --no-debug
  
  deploy-production:
    working_directory: /home/circleci
    docker:
      - image: cimg/php:8.1.9
    environment:
      CIRCLE_REPOSITORY_URL: https://softdev-nord:${BITBUCKET_PASSWORD}@bitbucket.org/softdev-nord/webwms.git
    steps:
      - envsubst/install
      - run: sudo apt update
      - run: sudo apt install openssh-client rsync
      - run:
          name: "Checkout code"
          command: |
            cd $CIRCLE_WORKING_DIRECTORY && \
            git clone -b << pipeline.git.branch >> "$CIRCLE_REPOSITORY_URL"
      - run:
          name: "Setup custom environment variables (.env)"
          command: |
            cd webwms/
            ci/set-env.sh
      - add_ssh_keys:
          fingerprints:
            - 33:9a:1d:5a:5c:6e:a4:0f:5f:ac:3c:83:8c:46:3c:fc
      - run: ssh-keyscan -H 178.20.100.70 >> ~/.ssh/known_hosts
      - run:
          name: Deploy production over SSH
          command: |
            rsync -ae ssh --exclude 'ci/rsync.exclude' \
            /home/circleci/webwms/ \
            admin_sodeno@178.20.100.70:/var/www/vhosts/softdev-nord.de/webwms.softdev-nord.de
      - run:
          name: Composer install
          command: |
            cd webwms/
            composer install --ignore-platform-reqs
      - run:
          name: Clear the caches
          command: |
            cd webwms/
            php bin/console cache:clear --no-debug

# Aufträge über Workflows aufrufen
# Siehe: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
    build-deploy:
      jobs:
        - build
        - deploy-development:
            context:
              - secrets
            filters:
              branches:
                only:
                  - development
            requires:
              - build
        - deploy-production:
            context:
              - secrets
            filters:
              branches:
                only:
                  - master
            requires:
              - build