#index:
#    path: /
#    controller: WebWMS\Controller\DefaultController::index

article:
    path: /artikel
    controller: WebWMS\Controller\Article::index

orders:
    path: /bestellungen
    controller: WebWMS\Controller\Order::index

orders_ajax:
    path: /orders_ajax
    controller: WebWMS\Controller\Order::getAllOrders

order_pos_ajax:
    path: /order_pos_ajax
    controller: WebWMS\Controller\Order::getAllOrderPos
