#index:
#    path: /
#    controller: WebWMS\Controller\DefaultController::index

article:
    path: /artikel
    controller: WebWMS\Controller\ArticleController::index

article_ajax:
    path: /article_ajax
    controller: WebWMS\Controller\ArticleController::getAllArticles

show_stock_location_details:
    path: /show_stock_location_details
    controller: WebWMS\Controller\StockController::getSockLocationDetailsById

stock_inventory_start:
    path: /inventur_starten
    controller: WebWMS\Bundles\StockInventoryBundle\Controller\DefaultController::index

stock_inventory_post:
    path: /inventur_starten
    controller: WebWMS\Bundles\StockInventoryBundle\Controller\DefaultController::index

stock_inventory_close:
    path: /inventur_starten
    controller: WebWMS\Bundles\StockInventoryBundle\Controller\DefaultController::index

stock_in_final:
    path: /stock_in_final
    controller: WebWMS\Controller\StockTransactionController::stockInFinal

dashboard:
    path: /dashboard
    controller: WebWMS\Controller\DashboardController::index

web_wms_log_viewer:
    path: /logs
    controller: WebWMS\Bundles\LogViewerBundle\Controller\LogViewerController::index

web_wms_log_viewer_logs:
    path: /logs/{file}
    controller: WebWMS\Bundles\LogViewerBundle\Controller\LogViewerController::logs