display_errors = On
expose_php = off
max_execution_time = 360
max_input_time = 360
memory_limit = 4096M
upload_max_filesize = 128M
post_max_size = 128M
safe_mode = Off
allow_url_fopen = On
#extension="imagick.so"
