display_errors = off
expose_php = off
max_execution_time = 360
max_input_time = 360
memory_limit = 1G
upload_max_filesize = 2M
post_max_size = 8M
safe_mode = Off
allow_url_fopen = On
#extension="imagick.so"
