<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB40ODG0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB40ODG0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB40ODG0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB40ODG0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB40ODG0\App_KernelDevDebugContainer([
    'container.build_hash' => 'B40ODG0',
    'container.build_id' => 'f11ed160',
    'container.build_time' => 1600591427,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB40ODG0');
