#name: CI
#
#on:
#  pull_request:
#    branches:
#      - '**'
#  workflow_dispatch:
#
#jobs:
#  symfony:
#    name: Symfony (PHP ${{ matrix.php-versions }})
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: true
#      matrix:
#        php-versions: ['8.3']
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Add composer auth credentials
#        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json
#
#      - name: Setup SSH Keys and known_hosts
#        env:
#          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
#        run: |
#          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
#          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
#
#      # https://github.com/shivammathur/setup-php (community)
#      - name: Setup PHP, extensions and composer with shivammathur/setup-php
#        uses: shivammathur/setup-php@verbose
#        with:
#          php-version: ${{ matrix.php-versions }}
#          extensions: mbstring, xml, ctype, iconv, intl, dom, filter, gd, iconv, json, mbstring, pdo, curl, amqp
#
#      # Composer
#      - name: Get composer cache directory
#        id: composer-cache
#        working-directory: .
#        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
#
#        # https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows
#      - name: Cache composer dependencies
#        uses: actions/cache@v4
#        with:
#          path: ${{ steps.composer-cache.outputs.dir }}
#          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
#          restore-keys: ${{ runner.os }}-composer-
#
#      - name: Setup Symfony
#        run: cp .env.template .env
#
#      - name: Install Composer dependencies
#        working-directory: .
#        env:
#          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
#        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
#
#      - name: Check PSR12 code style (Easy Coding Standards)
#        working-directory: .
#        run: composer run ecs
#
#      - name: Analyses PHP Code (PHP Mess Detector)
#        working-directory: .
#        run: composer run phpmd
#
#      - name: Analyse PHP Code (PHPStan)
#        working-directory: .
#        run: composer run phpstan